### ISSUE TITLE
Import error in React 16

### ISSUE THREAD

**Issue by jonathanstokes** [makannew/auto-scroll-container#1]
This is a cool project, I think it fulfills a need concisely. This might be a version or typescript incompatibility, but in React `16.10.2` when I do
```tsx
import MyComponent from 'auto-scroll-container';
```
I get
```
Attempted import error: 'auto-scroll-container' does not contain a default export (imported as 'MyComponent').
```

**Comment by makannew** [comment]
Sorry for late response, the truth is it isn't deployed yet!, sorry again.  I was testing how to build npm packages, and honestly I didn't expect anybody look at it. 

I am going to finish and deploy it very soon. Thanks @jonathanstokes I will be more careful in future.

**Comment by makannew** [comment]
V2.0.0 published, now is working.
